extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js



extra_css:
  - ./css/styles.css

site_name: SIP

theme:
  name: material
  language: es
  logo: ./assets/logoCut.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs.sticky
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - navigation.footer
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  homepage: 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/emepeweb

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  
nav:
  - Bienvenida: index.md
  - Portales:
    - Inicio: portales/inicio.md
    - Testigos: portales/testigos.md
    - Cliente: portales/cliente.md
  - Oferta: 
    - Sitios: oferta/sitios.md
    - Disponibilidad: oferta/disponibilidad.md
    - Planea tu campaña: oferta/planea.md
    - Propuestas de clientes: oferta/propuestas.md
    - Bloqueos: oferta/bloqueos.md
    - Cotizaciones: oferta/cotizaciones.md
  - Ventas:
    - Análisis Financieros: ventas/analisis.md
    - Testigos: ventas/testigos.md
    - Objetivos Vendadores: ventas/objetivos.md
    - Ordenes de venta: ventas/ordenes.md
    - Operaciones: ventas/operaciones.md
  - Facturación:
    - Generar Solicitud: facturacion/solicitud.md
    - Buscador de Facturas: facturacion/buscador.md
  - Dashboard:
    - Dashboard Comercial: dashboard/comercial.md
    - Dashboard Impresiones: dashboard/impresiones.md
    - Dashboard Operaciones: dashboard/operaciones.md
  - Contactos:
    - Clientes: contactos/clientes.md
    - Asociar Cliente a Vendedor: contactos/asociar.md
    - Convenios: contactos/convenios.md
    - Proveedores: contactos/proveedores.md
    - Agencias: contactos/agencias.md
    - Tarifas: contactos/tarifas.md
  - Operaciones:
    - Empleados: operaciones/empleados.md
    - Cuadrillas: operaciones/cuadrillas.md
    - Mantenimiento: operaciones/mantenimiento.md
    - Inventario: operaciones/inventario.md
    - Administrar Impresiones: operaciones/admin_impresiones.md
    - Ejecutar Impresiones: operaciones/exec_impresiones.md
    - Recibir Material: operaciones/recibirMaterial.md
  - Catálogos:
    - Sectores: catalogos/sectores.md
    - Tipos de clientes: catalogos/t_clientes.md
    - Tipos de proveedores: catalogos/t_proveedores.md
    - Tipos de Sitios: catalogos/t_sitios.md
    - Tipos de Vistas: catalogos/t_vistas.md
    - Tipos de Materiales: catalogos/t_materiales.md
    - Empresas: catalogos/empresas.md
    - Bancos: catalogos/bancos.md
    - Almacenes: catalogos/almacenes.md
    - Ciudades: catalogos/ciudades.md
    - Estructuras: catalogos/estructuras.md
  - Clasificación:
    - Plataformas de sitios: clasificacion/plataformas.md
    - Clasificación de sitios: clasificacion/clasificacion.md
  - Sistema:
    - Configuración: sistema/config.md
    - Usuarios: sistema/users.md
  - Sobre el Desarrollo: desarrollo.md


  


copyright:  |
  &copy; 2025 <a href="https://www.emepeweb.com/" target="_blank" rel="noopener">eme.pe</a>