extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js


extra_css:
  - /css/styles.css

site_name: SIP
theme:
  name: material
  language: es
  logo: /assets/logoCut.png    # Logo predeterminado
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.tabs.sticky
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/emepeweb

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  
nav:
  - Bienvenida: bienvenida.md
  - Inicio:
    - Introducción: inicio.md
    - Página 1: inicio/pg1.md
    - Página 2: inicio/pg2.md
  - Oferta: oferta.md
  - Ventas: ventas.md
  - Contactos: contactos.md
  - Personal: personal.md
  - Catálogos: catalogos.md
  - Clasificación: clasificacion.md
  - Sistema: sistema.md
  - dev tools: index.md


  


copyright:  |
  &copy; 2025 <a href="https://www.linkedin.com/in/carlos-guardiola-espinosa/" target="_blank" rel="noopener">Carlos Alejandro Guardiola Espinosa</a>

  <a>   &   </a>

  <a href="https://github.com/SmolBam-git" target="_blank" rel="noopener">Iván David López Solís</a>