extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js


extra_css:
  - /css/styles.css

site_name: SIP
theme:
  name: material
  language: es
  logo: /assets/logoCut.png    # Logo predeterminado
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/emepeweb

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.extra
  - attr_list
  


copyright:  |
  &copy; 2025 <a href="https://www.linkedin.com/in/carlos-guardiola-espinosa/" target="_blank" rel="noopener">Carlos Alejandro Guardiola Espinosa</a>

  <a>   &   </a>

  <a href="https://github.com/SmolBam-git" target="_blank" rel="noopener">Iván David López Solís</a>